### ISSUE TITLE
futures missing from Pipfile?

### ISSUE THREAD

**Issue by nbdavies** [openelections/openelections-core#267]
When I activate the pipenv environment, any openelex commands error out:
```
openelections-core [dev] :> pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
openelections-core [dev] :> source /Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/bin/activate
(openelections-core-D6msbyg9) openelections-core [dev] :> openelex --help
Traceback (most recent call last):
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/bin/openelex", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3144, in <module>
    @_call_aside
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
    f(*args, **kwargs)
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/ndavies/.virtualenvs/openelections-core-D6msbyg9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures>=2.1.3' distribution was not found and is required by requests-futures
```

I can move on by doing:
```
pipenv install futures
```
That modifies the Pipfile and Pipfile.lock. Is that the right solution? Has anyone else noticed this?

**Comment by dwillis** [comment]
Hey @nbdavies: I haven't experienced that myself. Was this a first-time thing?

**Comment by dwillis** [comment]
A second user reported the same thing, so consider this an actual bug.

**Comment by wismer** [comment]
@dwillis Having just installed this myself, I did encounter the `DistributionNotFound` error, but I think all that's missing is in the setup documentation. A `pip install -r requirements.txt` remedied it for me. FWIW, the actual dependency I was missing was `readline`, not `futures`. Not sure if that matters or not.
